### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tingmumu** [Particle-Network/particle-react-native#2]
![image](https://user-images.githubusercontent.com/15106073/236615095-3fc8c9b2-9e53-479e-a40d-a001a060603b.png)

Xcode：14.2
MacOS：13.3.1 (a) (22E772610a)

**Comment by SunZhiC** [comment]
Compare your Podfile with [Podfile](https://github.com/Particle-Network/particle-react-native/blob/master/particle-auth/example/ios/Podfile ) in example.
Then make sure `pod install --repo-update` could run without any error.
Maybe you need clean xcode cache before.
