### ISSUE TITLE
The Provider does not support the requested method

### ISSUE THREAD

**Issue by chenweigh** [Particle-Network/particle-react-native#22]
### code
```
web3_wallet_switchEthereumChain = async () => {
    try {
        const chainId = "0x" + EvmService.currentChainInfo.chain_id.toString(16);
        const result = await web3.currentProvider.request({
            method: 'wallet_switchEthereumChain',
            params: [{ chainId }]
        })
        console.log('web3 wallet_switchEthereumChain', result);
    } catch (error) {
        console.log('web3 wallet_switchEthereumChain', error);
    }

}

web3_wallet_addEthereumChain = async () => {
    try {
        const chainId = "0x" + EvmService.currentChainInfo.chain_id.toString(16);
        const result = await web3.currentProvider.request({
            method: 'wallet_addEthereumChain',
            params: [{ chainId }]
        })
        console.log('web3 wallet_addEthereumChain', result);
    } catch (error) {
        console.log('web3 wallet_addEthereumChain', error);
    }

}
```

### Problem
{
    "code": 4200,
    "message": "The Provider does not support the requested method"
}

**Comment by SunZhiC** [comment]
Do not support method wallet_addEthereumChain, all chains are defined in the chainInfo, cant add in runtime.
wallet_switchEthereumChain should work.

**Comment by chenweigh** [comment]
@SunZhiC  after connect metamask,   OpBNB-TestNet(5611),  send transaction，error：1 not permission on chain eip155:5611 or method eth_sendTransaction . the reason: metamask  have no 5611 chain. 
I need auto add chain 5611  to metamask, and switch the chain 5611， as chrome plugin metamask.
![截屏2024-02-27 12 01 14](https://github.com/Particle-Network/particle-react-native/assets/15101298/3e6b453a-fb4a-4a88-a701-b4e44ddef409)

**Comment by SunZhiC** [comment]
Yes, you have to add the OPBNB chain to metamask by hand.
