### ISSUE TITLE
particleConnect not exist “switchEthereumChain” attr.

### ISSUE THREAD

**Issue by chenweigh** [Particle-Network/particle-react-native#24]
![截屏2024-04-03 18 16 54](https://github.com/Particle-Network/particle-react-native/assets/15101298/f28bd0c4-7359-4f77-8f69-8f22c26d1178)

**Comment by SunZhiC** [comment]
These two methods were removed from wallet connect 2.0 SDK, then we removed from our SDK.
Base on wallet connect 2.0, you can connect more than one chain in a connection.
But metamask does not support connect more then one chain.
Other wallets work well.
