### ISSUE TITLE
smartAccountAddress showing undefined 

### ISSUE THREAD

**Issue by majednitol** [Particle-Network/particle-react-native#25]
{"avatar": "*****c", "created_at": "2024-04-15T14:25:31.000Z", "google_email": "[majedur15-108@diu.edu.bd](mailto:majedur15-14708@diu.edu.bd)", "google_id": "116779180351951502819", "name": "Md. Majedur Rahman 212-15-14708", "security_account": {"has_set_master_password": false, "has_set_payment_password": false}, "thirdparty_user_info": {"provider": "google", "user_info": {"email": "****](****)", "id": "116779180351951502819", "name": "Md. Majedur Rahman 212-15-14708", "picture": "*****rAG1TWEBlTw0=s96-c"}}, "token": "523b8075-157e-4805-a025-63374916822d", "updated_at": "2024-04-15T14:25:31.000Z", "uuid": "e815e7da-4b13-4fa2-a330-f613a28bbdd5", "wallets": [{"chain_name": "solana", "public_address": "", "uuid": "c88ed615-fdc0-4fed-8f13-c7649c54b00a"}, {"chain_name": "evm_chain", "public_address": "********", "uuid": "4a26aea0-30ba-48d3-a4bb-53ef2e"}]}
 LOG  is enable true
 LOG  request body = {"id":"1713205766068","jsonrpc":"2.0","method":"particle_aa_getSmartAccount","params":[{"name":"BICONOMY","version":"1.0.0","ownerAddress":"0x5aED9Eb****"2DC86d647a"}],"chainId":421614}
 LOG  response result = undefined
 LOG  result {"data": {"code": 0, "data": "System error"}, "status": 0}
 LOG  smartAccountAddress undefined in **particle-aa** project

**Comment by SunZhiC** [comment]
biconomy 1.0.0 does not support 421614, you can try biconomy 2.0.0 or simple 1.0.0.

**Comment by majednitol** [comment]
![IMG_20240416_095307_842](https://github.com/Particle-Network/particle-react-native/assets/78228005/cd044d00-0088-42f0-93dc-dd03df38be1a)

I didn't install biconomy package. I just  try to run your demo project.

**Comment by SunZhiC** [comment]
you don't need install biconomy package, you should select BICONOMY_V2 or SIMPLE.
such as
```
accountName = AccountName.BICONOMY_V2();
```

**Comment by majednitol** [comment]
How can i use testnet for paymaster ?  How can i understand which account will pay  all user gas fee.

**Comment by SunZhiC** [comment]
> How can i use testnet for paymaster ? How can i understand which account will pay all user gas fee.

for testnet, when sending transaction, you can select gasless, we can pay the gas fee. 
for mainnet, in particle dashboard, we support deposit USDT in BNB chain mainnet or Ethereum mainnet, then you can try send gasless in other mainnet, it means we pay for the gas fee.
