### ISSUE TITLE
Update @particle-network/chains to version 1.4.15 or above.

### ISSUE THREAD

**Issue by beanu** [Particle-Network/particle-react-native#26]
Please help to update @particle-network/chains to the latest version(1.4.15+) to support the IoTeX network. Thank you!

**Comment by SunZhiC** [comment]
You can add "@particle-network/chains": "^1.5.2" to your package.json dependencies.

**Comment by beanu** [comment]
@SunZhiC Yes, I added a dependency on “@particle-network/chains” version 1.4.15 or 1.5.2, but when I log in on iOS (calling `particleAuth.login`), the app crashes. The Android system can call it normally.

Noted that: When `chainInfo = EthereumSepolia`, and logging in is normal. However, when switching to the Iotex chain, an abnormal situation occurred.

> const chainInfo = IoTeX;
> const env = Env.Production;
> particleAuth.init(chainInfo, env);


The following is the error message.
![ERROR](https://github.com/Particle-Network/particle-react-native/assets/1559643/38d2643c-c206-4cb9-a463-1698897b51ef)

**Comment by SunZhiC** [comment]
> @SunZhiC Yes, I added a dependency on “@particle-network/chains” version 1.4.15 or 1.5.2, but when I log in on iOS (calling `particleAuth.login`), the app crashes. The Android system can call it normally.
> 
> Noted that: When `chainInfo = EthereumSepolia`, and logging in is normal. However, when switching to the Iotex chain, an abnormal situation occurred.
> 
> > const chainInfo = IoTeX;
> > const env = Env.Production;
> > particleAuth.init(chainInfo, env);
> 
> The following is the error message. ![ERROR](https://private-user-images.githubusercontent.com/1559643/344403307-38d2643c-c206-4cb9-a463-1698897b51ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MTQ2NTMsIm5iZiI6MTcxOTcxNDM1MywicGF0aCI6Ii8xNTU5NjQzLzM0NDQwMzMwNy0zOGQyNjQzYy1jMjA2LTRjYjktYTQ2My0xNjk4ODk3YjUxZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MzBUMDIyNTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2RmZjhiMzQ4NGI1MTc4MWMwZGNlMmE0YThhOTk3NGYyMTRlMWQwYWZjYTAzYTk4MDdhNThiYjE3ZTljYmExNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zN55_TW3GIcuJrfTLjUURy2B7hU4l7WJOTm-YutKDGA)

Update your Podfile, specify pod 'ParticleNetworkBase', '1.4.8'

**Comment by beanu** [comment]
@SunZhiC After several try, it kept reporting errors.
![error](https://github.com/Particle-Network/particle-react-native/assets/1559643/b27d7c67-4feb-4635-9059-e3308a220200)

**Comment by SunZhiC** [comment]
> @SunZhiC After several try, it kept reporting errors.
> 
> ![error](https://github.com/Particle-Network/particle-react-native/assets/1559643/b27d7c67-4feb-4635-9059-e3308a220200)
> 
> 

The SDK doesn't support simulators, should be running on a real iPhone.

**Comment by beanu** [comment]
@SunZhiC Yes, can you take a look at this issue? I am running it on a real iPhone.

The Podfile

> pod 'ParticleAuthService', '1.4.8'
>   pod 'ParticleNetworkBase', '1.4.8'
>   pod 'ParticleWalletGUI', '1.4.8'
>   pod 'ParticleWalletAPI', '1.4.8'
>   pod 'ParticleWalletConnect', '1.4.8'
> 
>   pod 'ParticleConnect', '0.2.24'
>   pod 'ConnectWalletConnectAdapter', '0.2.24'
>   pod 'ConnectEVMAdapter', '0.2.24'
>   pod 'ConnectSolanaAdapter', '0.2.24'
>   pod 'ConnectPhantomAdapter', '0.2.24'
>   pod 'ConnectCommon', '0.2.24'
>   pod 'ParticleAuthAdapter', '0.2.24'
 
 package.json

>   "@particle-network/rn-auth": "1.4.12",
>     "@particle-network/rn-connect": "1.4.12",
>     "@particle-network/rn-wallet": "1.4.12",

I did not use the `particle_auth_core` library.

**Comment by SunZhiC** [comment]
> @SunZhiC Yes, can you take a look at this issue? I am running it on a real iPhone.
> 
> 
> 
> The Podfile
> 
> 
> 
> > pod 'ParticleAuthService', '1.4.8'
> 
> >   pod 'ParticleNetworkBase', '1.4.8'
> 
> >   pod 'ParticleWalletGUI', '1.4.8'
> 
> >   pod 'ParticleWalletAPI', '1.4.8'
> 
> >   pod 'ParticleWalletConnect', '1.4.8'
> 
> > 
> 
> >   pod 'ParticleConnect', '0.2.24'
> 
> >   pod 'ConnectWalletConnectAdapter', '0.2.24'
> 
> >   pod 'ConnectEVMAdapter', '0.2.24'
> 
> >   pod 'ConnectSolanaAdapter', '0.2.24'
> 
> >   pod 'ConnectPhantomAdapter', '0.2.24'
> 
> >  pod 'ConnectCommon', '0.2.24'
> 
> >   pod 'ParticleAuthAdapter', '0.2.24'
> 
>  
> 
>  package.json
> 
> 
> 
> >   "@particle-network/rn-auth": "1.4.12",
> 
> >     "@particle-network/rn-connect": "1.4.12",
> 
> >     "@particle-network/rn-wallet": "1.4.12",
> 
> 
> 
> I did not use the `particle_auth_core` library.

Can you check what is the version of SDWebImageSwiftUI in your Podfile.lock, they released a new version 3.10 days ago, I suppose they did changed some interface structure, which caused this error. 
You can try to add 
`pod 'SDWebImageSwiftUI', '3.0.4' ` to fix it.

**Comment by beanu** [comment]
It's working. Thanks a lot.

**Comment by beanu** [comment]
> > @SunZhiC Yes, can you take a look at this issue? I am running it on a real iPhone.
> > The Podfile
> > > pod 'ParticleAuthService', '1.4.8'
> > 
> > 
> > > pod 'ParticleNetworkBase', '1.4.8'
> > 
> > 
> > > pod 'ParticleWalletGUI', '1.4.8'
> > 
> > 
> > > pod 'ParticleWalletAPI', '1.4.8'
> > 
> > 
> > > pod 'ParticleWalletConnect', '1.4.8'
> > 
> > 
> > > 
> > 
> > 
> > > pod 'ParticleConnect', '0.2.24'
> > 
> > 
> > > pod 'ConnectWalletConnectAdapter', '0.2.24'
> > 
> > 
> > > pod 'ConnectEVMAdapter', '0.2.24'
> > 
> > 
> > > pod 'ConnectSolanaAdapter', '0.2.24'
> > 
> > 
> > > pod 'ConnectPhantomAdapter', '0.2.24'
> > 
> > 
> > > pod 'ConnectCommon', '0.2.24'
> > 
> > 
> > > pod 'ParticleAuthAdapter', '0.2.24'
> > 
> > 
> > package.json
> > > "@particle-network/rn-auth": "1.4.12",
> > 
> > 
> > > ```
> > > "@particle-network/rn-connect": "1.4.12",
> > > ```
> > 
> > 
> > > ```
> > > "@particle-network/rn-wallet": "1.4.12",
> > > ```
> > 
> > 
> > I did not use the `particle_auth_core` library.
> 
> Can you check what is the version of SDWebImageSwiftUI in your Podfile.lock, they released a new version 3.10 days ago, I suppose they did changed some interface structure, which caused this error. You can try to add `pod 'SDWebImageSwiftUI', '3.0.4' ` to fix it.


It's working. Thanks a lot.
