### ISSUE TITLE
Unable to switch to the newly added chain.

### ISSUE THREAD

**Issue by beanu** [Particle-Network/particle-react-native#27]
After updating `"@particle-network/chains": "^1.4.15"`, running the demo of Auth and switching to the newly added chain will cause an error. 

The specific operation process is as follows:
> 1. particleAuth.init(chainInfo, env);
> 2. particleAuth.login(type, '', supportAuthType);
> 3. // Select chain (IOTEX or SEI)
> 4. particleAuth.setChainInfo(chainInfo)

Only appearing in the **Android** environment.

![WX20240702-111330@2x](https://github.com/Particle-Network/particle-react-native/assets/1559643/2908ee2a-9228-434f-9263-4c6de938fb70)

**Comment by xxhong** [comment]
fix in 1.4.13
