### ISSUE TITLE
Android blank screen issue on confirmation screen

### ISSUE THREAD

**Issue by sbalcin** [Particle-Network/particle-react-native#4]
particle-auth screen remains blank without any error message in Android while interacting with the contract method, same flow works fine in IOS. Is there any way to see what's wrong, thanks

<img width="415" alt="Screenshot 2023-07-28 at 10 34 54" src="https://github.com/Particle-Network/particle-react-native/assets/6813922/5be2b275-b69b-40ae-adb2-02ac07cb52a0">

**Comment by sbalcin** [comment]
same blank screen in android auth example of yours as well, is it about react native version ? have you test it before ?

**Comment by sbalcin** [comment]
it may be about encoding for Android like the library does for signMessage;
`HexUtils.encodeWithPrefix(message.toByteArray(Charsets.UTF_8))`
which is not exist on IOS side. 
But contract methods handled in the following service which is not public:
`network.particle:auth-service:...`
could you please check that service or comment about the issue

**Comment by xxhong** [comment]
try with 1.0.4
